---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: container
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "You've almost completed the challenge. Keep going!"
              sleep infinity
        - name: container-2
          image: busybox
          readinessProbe:
            timeoutSeconds: 31
            failureThreshold: 3
            successThreshold: 1
            exec:
              command:
                - test
                - -f
                - /tmp/ready
          command:
            - sh
            - -c
            - |
              sleep 30
              touch /tmp/ready
              echo "You've completed the challenge. Nice work!"
              sleep infinity
