# This configuration will create a Kubernetes
# cluster with a single worker that only has
# 1Gi available for Pods.
#
# If the cluster fails to create, adjust
# the amount of memory next to `system-reserved` to something lower.
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
  - role: control-plane
  - role: worker
networking:
  disableDefaultCNI: true
