apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  tolerations:
    - effect: NoSchedule
      operator: Exists
      key: debugging.k8s.io/ready
  containers:
    - image: busybox
      name: container
      command:
        - echo
        - "Hello!"
      resources:
        limits:
          memory: 256Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: test-app-2
  labels:
    app: test-app-2
spec:
  tolerations:
    - effect: NoSchedule
      operator: Exists
      key: debugging.k8s.io/ready
  containers:
    - image: busybox
      name: container
      command:
        - echo
        - "Hello!"
      resources:
        limits:
          memory: 128Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-app-3-pvc
  labels:
    app: test-app-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: test-app-3
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app-3
  labels:
    app: test-app-3
spec:
  tolerations:
    - effect: NoSchedule
      operator: Exists
      key: debugging.k8s.io/ready
  containers:
    - image: busybox
      name: container
      command:
        - echo
        - "Hello!"
      resources:
        limits:
          memory: 128Mi
