apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-app-3
  name: test-app-3
  namespace: default
spec:
  containers:
  - command:
    - echo
    - Hello!
    image: busybox
    imagePullPolicy: Always
    name: container
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: debugging.k8s.io/ready
    operator: Exists
